---
title: "Historical Severity Statistics"
author: "SAJ"
date: "1/7/2022"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=F}
# import libraries
library(fiphde)
library(cdcfluview)
library(dplyr)
library(ggplot2)
library(fitdistrplus)
```

```{r}
# pull data from cdcfluview
hosp <- cdcfluview::hospitalizations(surveillance_area = "flusurv",
                                     region="all")

# visualize data to get oriented
hosp %>% 
  filter(age_label == "Overall") %>% 
  filter(year %>% between(2010, 2021)) %>%
  mutate("counts" = as.numeric(weeklyrate)*3330) %>%
  dplyr::select(c("wk_start", "counts", "year_wk_num")) %>%
  rename(EpiWeek = year_wk_num) %>%
  ggplot(aes(x = sort(wk_start), y = as.numeric(counts))) + 
  geom_point(aes(color = EpiWeek)) +
  xlab("Date") +
  ylab("Hospitilzation Counts")

# for every epiweek, calculate fivenum based on count dist
hospStats <-
  hosp %>% 
    filter(age_label == "Overall") %>% 
    filter(year %>% between(2010, 2021)) %>%
    mutate("counts" = as.numeric(weeklyrate)*3300) %>%
    dplyr::select(c("wk_start", "counts", "year_wk_num")) %>%
    rename(EpiWeek = year_wk_num) %>%
    group_by(EpiWeek) %>%
    summarise(Minimum = min(counts),
              LowerHinge = IQR(counts, 0.25),
              Median = median(counts),
              UpperHinge = IQR(counts, 0.75),
              Mean = mean(counts))
hospStats
```

```{r}
# # distribution fit tests
# # create vector of counts
# CountsDF <- 
#   hosp %>% 
#     filter(age_label == "Overall") %>%
#     filter(year %>% between(2010, 2019)) %>%
#     #rename(EpiWeek = year_wk_num) %>%
#     mutate("counts" = as.numeric(rate)*100000)
# CountsVec <- CountsDF$counts
# 
# # see what dist might fit
# descdist(CountsVec, discrete = F)
# 
# # transform the counts to fit beta range (0,1)
# # note: adding tiny value to allow fitdist to not calculate inf/-inf
# range01 <- function(x){(x - min(x) + 0.001)/(max(x) - min(x) + 0.002)}
# 
# # fit dists
# fit.beta <- fitdist(range01(CountsVec), "beta")
# fit.norm <- fitdist(CountsVec, "norm")
# 
# # first look at norm, doesn't look great
# plot(fit.norm)
# 
# # now look at beta, definitely more plausible
# plot(fit.beta)
```
