## usethis namespace: start
#' @importFrom rlang .data
#' @importFrom rlang .env
#' @keywords internal
"_PACKAGE"

## quiets concerns of R CMD check re: the non-bound global variables
if(getRversion() >= "2.15.1")  utils::globalVariables(c(".",
                                                        "previous_day_admission_influenza_confirmed",
                                                        "previous_day_admission_influenza_confirmed_coverage",
                                                        "previous_day_deaths_influenza",
                                                        "previous_day_deaths_influenza_coverage",
                                                        "icu_patients_confirmed_influenza",
                                                        "icu_patients_confirmed_influenza_coverage",
                                                        "total_patients_hospitalized_confirmed_influenza",
                                                        "total_patients_hospitalized_confirmed_influenza_coverage",
                                                        "previous_day_admission_adult_covid_confirmed",
                                                        "previous_day_admission_adult_covid_confirmed_coverage",
                                                        "deaths_covid",
                                                        "deaths_covid_coverage",
                                                        "cov.deaths.cov",
                                                        "current_through",
                                                        "week",
                                                        "cumulative_flu_doses_distributed",
                                                        "month",
                                                        "season",
                                                        "y1",
                                                        "y2",
                                                        "year",
                                                        "month_calendar_number",
                                                        "month_number",
                                                        "epiyear",
                                                        "epiweek",
                                                        "imputed_value",
                                                        "region_type",
                                                        "week_start",
                                                        "ilitotal",
                                                        "total_patients",
                                                        "location",
                                                        "abbreviation",
                                                        "age_label",
                                                        "year_wk_num",
                                                        "wk_start",
                                                        "wk_end",
                                                        "rate",
                                                        "weeklyrate",
                                                        "sea_label",
                                                        "monday",
                                                        "yweek",
                                                        "weighted_ili",
                                                        ".mean",
                                                        "0.025",
                                                        "0.975",
                                                        "<NA>",
                                                        "error",
                                                        "estimate",
                                                        "model",
                                                        "lower",
                                                        "upper",
                                                        "lower_pi",
                                                        "upper_pi",
                                                        "flu.admits",
                                                        "quantile",
                                                        "truth",
                                                        "rmse",
                                                        "value",
                                                        "unweighted_ili",
                                                        "ili",
                                                        "miss",
                                                        "total",
                                                        "pmiss",
                                                        "arima",
                                                        "state",
                                                        "flu.admits.cov",
                                                        "week_end",
                                                        "location_name",
                                                        "population",
                                                        "x",
                                                        "MMWRyear",
                                                        "MMWRweek",
                                                        "std",
                                                        "dates_to_replace",
                                                        "region",
                                                        "weighted_ili_now",
                                                        "ets",
                                                        ".model",
                                                        "key",
                                                        "N",
                                                        "forecast_date",
                                                        "target",
                                                        "target_end_date",
                                                        "type",
                                                        "point",
                                                        "horizon_days",
                                                        "ind",
                                                        "quants",
                                                        "targets",
                                                        "expected_sat",
                                                        "horizon",
                                                        ".submission_dir",
                                                        "is_null_model",
                                                        "mmwrid_map",
                                                        ".surv_map",
                                                        ".region_map",
                                                        "wk_date",
                                                        "total_specimens",
                                                        "total_positive",
                                                        "total_a",
                                                        "total_b",
                                                        "percent_positive",
                                                        "n_positive",
                                                        "type_id",
                                                        "lag_rate",
                                                        "lag_value",
                                                        "race_label",
                                                        "sexid",
                                                        "name",
                                                        "weeknumber",
                                                        "weekend",
                                                        "weekstart",
                                                        "season_label",
                                                        "catchmentid",
                                                        "increase",
                                                        "large_increase",
                                                        "decrease",
                                                        "large_decrease",
                                                        "stable",
                                                        "score",
                                                        "loc",
                                                        "models",
                                                        "model_name",
                                                        "nas_removed",
                                                        "output_type",
                                                        "output_type_id",
                                                        "reference_date",
                                                        "target_name",
                                                        "target_prob",
                                                        "nnetar",
                                                        "mean_flu_admits",
                                                        "Geographic aggregation",
                                                        "Total Influenza Admissions",
                                                        "max_reporting",
                                                        "flu.admits.cov.perc",
                                                        "hosp_mean",
                                                        "hosp_rank",
                                                        "ili_mean",
                                                        "ili_rank",
                                                        "Week Ending Date",
                                                        "Percent Hospitals Reporting Influenza Admissions",
                                                        "Percent Hospitals Reporting  Influenza Admissions",
                                                        "Number Hospitals Reporting Influenza Admissions",
                                                        "Number Hospitals Reporting  Influenza Admissions",
                                                        "."))

